AWSTemplateFormatVersion: '2010-09-09'
Description: Configuracao de DNS no Route 53 para Frontend (CloudFront) e Backend (ALB).

Parameters:
  ProjetoNome:
    Type: String

  ProjetoNomeBackend:
    Type: String
    Default: "cadastro-aplicacao-prod"


  HostedZoneId:
    Type: String
    

  DominioNome:
    Type: String

    
  ALBDomain:
    Type: String
    

Resources:
  # =========================================================
  # FRONTEND (asantanadev.com) -> CloudFront
  # =========================================================
  FrontendRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${DominioNome}."
      Type: A
      AliasTarget:
        DNSName: !ImportValue 
          Fn::Sub: "${ProjetoNome}-CloudFrontURL" 
        HostedZoneId: Z2FDTNDATAQYW2 
        EvaluateTargetHealth: false

  # =========================================================
  # BACKEND (api.asantanadev.com) -> ALB
  # =========================================================
  BackendRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${ALBDomain}."
      Type: A
      AliasTarget:
        DNSName: !ImportValue 
          Fn::Sub: "${ProjetoNomeBackend}-AppURL"
        HostedZoneId: Z35SXDOTRQ7X7K 
        EvaluateTargetHealth: true

Outputs:
  SiteURL:
    Description: URL do frontend
    Value: !Sub "https://${DominioNome}"
  ApiURL:
    Description: URL da API
    Value: !Sub "https://${ALBDomain}"