AWSTemplateFormatVersion: '2010-09-09'
Description: ALB e Target Group - Porta de entrada pública com HTTPS (TLS)

Parameters:
  ProjetoNome:
    Type: String

  FundacaoStack:
    Type: String

  # ===============================
  # NOVO: Recebe o ARN do certificado
  # Vem do GitHub Actions (vars.CERTIFICATE_ARN)
  # Necessário para habilitar HTTPS no ALB
  # ===============================
  CertificateArn:
    Type: String
    Description: ARN do certificado TLS do ACM


Resources:

  # ===============================
  # Target Group (NÃO mudou)
  # Continua HTTP interno → ALB conversa com EC2 via 8080
  # HTTPS fica somente na borda (ALB)
  # ===============================
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ProjetoNome}-tg"
      Port: 8080
      Protocol: HTTP

      VpcId:
        Fn::ImportValue:
          !Sub "${FundacaoStack}-VpcId"

      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200

      TargetType: instance

      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'


  # ===============================
  # ALB público
  # ===============================
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ProjetoNome}-alb"

      Subnets:
        - Fn::ImportValue:
            !Sub "${FundacaoStack}-PublicSubnet1"
        - Fn::ImportValue:
            !Sub "${FundacaoStack}-PublicSubnet2"

      SecurityGroups:
        - Fn::ImportValue:
            !Sub "${FundacaoStack}-ALBSG"

      Type: application


  # ======================================================
  # NOVO: Listener HTTP (80)
  # Apenas redireciona para HTTPS
  # Padrão profissional: nunca servir HTTP direto
  # ======================================================
  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: 443
            StatusCode: HTTP_301


  # ======================================================
  # NOVO: Listener HTTPS (443)
  # Aqui usamos o certificado do ACM
  # Recebe tráfego público seguro
  # ======================================================
  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS

      Certificates:
        - CertificateArn: !Ref CertificateArn

      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup


Outputs:
  TargetGroupArn:
    Value: !Ref TargetGroup

  # Continua funcionando igual, agora servindo HTTPS
  AppURL:
    Value: !GetAtt LoadBalancer.DNSName
