AWSTemplateFormatVersion: '2010-09-09'
Description: ALB e Target Group - Porta de entrada pública com HTTPS corrigido.

Parameters:
  ProjetoNome:
    Type: String
  FundacaoStack:
    Type: String
  CertificateArn:
    Type: String
    Description: ARN do certificado TLS do ACM

Resources:

  # ===============================
  # Target Group (Ajustado para o Health Check do Spring)
  # ===============================
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ProjetoNome}-tg"
      Port: 8080
      Protocol: HTTP
      VpcId: 
        Fn::ImportValue: !Sub "${FundacaoStack}-VpcId"
      # Ajustado para bater com o seu application.properties
      HealthCheckPath: /actuator/health/readiness
      HealthCheckIntervalSeconds: 35
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5 # Aumentado para dar mais chances à instância no boot
      Matcher:
        HttpCode: '200'
      TargetType: instance
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'

  # ===============================
  # ALB público
  # ===============================
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ProjetoNome}-alb"
      Subnets:
        - Fn::ImportValue: !Sub "${FundacaoStack}-PublicSubnet1"
        - Fn::ImportValue: !Sub "${FundacaoStack}-PublicSubnet2"
      SecurityGroups:
        - Fn::ImportValue: !Sub "${FundacaoStack}-ALBSG"
      Type: application

  # ===============================
  # Listeners (HTTP -> HTTPS -> Forward)
  # ===============================
  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301

  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  TargetGroupArn:
    Description: ARN do Target Group para ser capturado pelo Master
    Value: !Ref TargetGroup

  AppURL:
    Description: URL pública via HTTPS
    Value: !GetAtt LoadBalancer.DNSName