AWSTemplateFormatVersion: '2010-09-09'
Description: ASG e Launch Template - Automação total com Secrets Manager e JQ.

Parameters:
  ProjetoNome:
    Type: String
  FundacaoStack:
    Type: String
  TargetGroupArn:
    Type: String

Resources:
  BackendLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${ProjetoNome}-lt"
      LaunchTemplateData:
        ImageId: ami-0c101f26f147fa7fd # Amazon Linux 2023 em us-east-1
        InstanceType: t3.micro

        IamInstanceProfile:
          Name: !ImportValue
            Fn::Sub: "${FundacaoStack}-InstanceProfile"

        SecurityGroupIds:
          - !ImportValue
              Fn::Sub: "${FundacaoStack}-BackendSG"

        UserData:
          Fn::Base64:
            Fn::Sub:
              - |
                #!/bin/bash
                set -euo pipefail

                # Log do UserData para debug
                exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

                echo "Iniciando provisionamento..."
                yum update -y
                yum install -y java-17-amazon-corretto-devel aws-cli jq

                # 1) Baixa o JAR do S3
                aws s3 cp s3://asantanadev-cfn-templates/app.jar /home/ec2-user/app.jar
                chown ec2-user:ec2-user /home/ec2-user/app.jar

                # 2) Cria o run.sh dinâmico (Consumindo Secrets Manager)
                cat > /home/ec2-user/run.sh <<'EOF'
                #!/bin/bash
                set -euo pipefail

                # Busca o JSON do segredo gerado pelo RDS
                SECRET_NAME="/${PROJETO_NOME}/prod/db/credentials"
                REGION="us-east-1"
                
                SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $SECRET_NAME --region $REGION --query SecretString --output text)

                # Extrai usuário e senha via JQ
                DB_USER=$(echo $SECRET_JSON | jq -r .username)
                DB_PASSWORD=$(echo $SECRET_JSON | jq -r .password)
                
                # Execução do Java com Dialeto e Endpoint dinâmico
                java -Xmx512m -jar /home/ec2-user/app.jar \
                  --spring.profiles.active=prod \
                  --spring.datasource.url="jdbc:postgresql://${DB_ENDPOINT}:5432/cadastros_usuario" \
                  --spring.datasource.username="$DB_USER" \
                  --spring.datasource.password="$DB_PASSWORD" \
                  --spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect \
                  --spring.datasource.hikari.initialization-fail-timeout=0
                EOF

                # Ajusta permissões
                chown ec2-user:ec2-user /home/ec2-user/run.sh
                chmod +x /home/ec2-user/run.sh

                # 3) Executa em background
                echo "Iniciando aplicação Java..."
                sudo -u ec2-user nohup /home/ec2-user/run.sh > /home/ec2-user/app-exec.log 2>&1 &
                
              - DB_ENDPOINT: !ImportValue
                  Fn::Sub: "${FundacaoStack}-DBEndpoint"
                PROJETO_NOME: !Ref ProjetoNome

  BackendASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${ProjetoNome}-asg"
      VPCZoneIdentifier:
        - !Select [0, !Split [",", !ImportValue {"Fn::Sub": "${FundacaoStack}-PrivateSubnets"}]]
        - !Select [1, !Split [",", !ImportValue {"Fn::Sub": "${FundacaoStack}-PrivateSubnets"}]]
      LaunchTemplate:
        LaunchTemplateId: !Ref BackendLaunchTemplate
        Version: !GetAtt BackendLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '2'
      TargetGroupARNs:
        - !Ref TargetGroupArn
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300

Outputs:
  AsgName:
    Value: !Ref BackendASG