AWSTemplateFormatVersion: '2010-09-09'
Description: Agregador Master da Fundação - Rede, Segurança e Banco.

Parameters:
  ProjetoNome:
    Type: String
  VpcCIDR:
    Type: String
  DBName:
    Type: String

Resources:
  StackRede:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://asantanadev-cfn-templates.s3.amazonaws.com/vpc.yaml
      Parameters:
        ProjetoNome: !Ref ProjetoNome
        VpcCIDR: !Ref VpcCIDR

  StackSeguranca:
    Type: AWS::CloudFormation::Stack
    DependsOn: StackRede
    Properties:
      TemplateURL: https://asantanadev-cfn-templates.s3.amazonaws.com/security-groups.yaml
      Parameters:
        ProjetoNome: !Ref ProjetoNome
        VpcId: !GetAtt StackRede.Outputs.VpcId

  StackBanco:
    Type: AWS::CloudFormation::Stack
    DependsOn: StackSeguranca
    Properties:
      TemplateURL: https://asantanadev-cfn-templates.s3.amazonaws.com/rds.yaml
      Parameters:
        ProjetoNome: !Ref ProjetoNome
        VpcId: !GetAtt StackRede.Outputs.VpcId
        PrivateSubnets: !GetAtt StackRede.Outputs.PrivateSubnets
        DBSecurityGroup: !GetAtt StackSeguranca.Outputs.DBSG
        DBName: !Ref DBName
        # CORREÇÃO: Removido DBUser e DBPassword daqui.

Outputs:
  VpcId:
    Value: !GetAtt StackRede.Outputs.VpcId
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"
  PublicSubnet1:
    Value: !GetAtt StackRede.Outputs.PublicSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1"
  PublicSubnet2:
    Value: !GetAtt StackRede.Outputs.PublicSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet2"
  PrivateSubnets:
    Value: !GetAtt StackRede.Outputs.PrivateSubnets
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnets"
  BackendSG:
    Value: !GetAtt StackSeguranca.Outputs.BackendSG
    Export:
      Name: !Sub "${AWS::StackName}-BackendSG"
  ALBSG:
    Value: !GetAtt StackSeguranca.Outputs.ALBSG
    Export:
      Name: !Sub "${AWS::StackName}-ALBSG"
  InstanceProfile:
    Value: !GetAtt StackSeguranca.Outputs.InstanceProfile
    Export:
      Name: !Sub "${AWS::StackName}-InstanceProfile"
  DBEndpoint:
    Value: !GetAtt StackBanco.Outputs.Endpoint
    Export:
      Name: !Sub "${AWS::StackName}-DBEndpoint"