AWSTemplateFormatVersion: '2010-09-09'
Description: RDS PostgreSQL v16.8 - Segurança Máxima e Rede Fluida.

Parameters:
  ProjetoNome:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  DBName:
    Type: String
  DBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBInstanceClass:
    Type: String
    Default: db.t3.micro

Resources:
  # Agrupamento de Subnets Privadas: Onde o banco reside com segurança
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub "Subnets privadas para o banco ${ProjetoNome}"
      SubnetIds: !Ref PrivateSubnets
      Tags:
        - Key: Name
          Value: !Sub "${ProjetoNome}-DB-Subnet-Group"

  # Instância de Banco de Dados com as travas de segurança corretas
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: "16.8" # Versão estável confirmada
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: "20"
      StorageType: gp3
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      PubliclyAccessible: false # Segurança Total: invisível para a internet
      BackupRetentionPeriod: 7
      DeleteAutomatedBackups: false # Evita perda de dados (Segurança de Estado)
      Tags:
        - Key: Name
          Value: !Sub "${ProjetoNome}-Database"

Outputs:
  Endpoint:
    Description: Host do banco para a variável DB_URL do Spring Boot
    Value: !GetAtt RDSInstance.Endpoint.Address