AWSTemplateFormatVersion: '2010-09-09'
Description: Configuração de Firewalls e Permissões - Alinhamento total com Secrets Manager.

Parameters:
  ProjetoNome:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:

  # =========================================================
  # SG do Load Balancer
  # =========================================================
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite entrada HTTP/HTTPS e SAIDA TOTAL
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${ProjetoNome}-alb-sg'

  # =========================================================
  # SG do Backend (Java)
  # =========================================================
  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Porta 8080 liberada para o ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${ProjetoNome}-backend-sg'

  # =========================================================
  # SG do Banco (RDS)
  # =========================================================
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Porta 5432 restrita ao Backend
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref BackendSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${ProjetoNome}-db-sg'

  # =========================================================
  # IAM ROLE DA EC2: Acesso ao Secrets Manager
  # =========================================================
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: ReadRDSSecretFromSecretsManager
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                # Acesso restrito ao novo cofre criado pelo RDS
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${ProjetoNome}/prod/db/credentials-*"
      Tags:
        - Key: Project
          Value: !Ref ProjetoNome

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

Outputs:
  InstanceProfile:
    Value: !Ref EC2InstanceProfile
  BackendSG:
    Value: !Ref BackendSecurityGroup
  DBSG:
    Value: !Ref DBSecurityGroup
  ALBSG:
    Value: !Ref ALBSecurityGroup
