run-dev:
	mvn spring-boot:run -Dspring-boot.run.profiles=dev

run-test:
	mvn spring-boot:run -Dspring-boot.run.profiles=test

test:
	mvn test -Dspring.profiles.active=test

clean:
	mvn clean

build:
	mvn clean install
